import { Inter } from "next/font/google";
import Providers from "@/Provider/Provider";
import "../styles/globals.css";
import Nav from "@/app/Components/Nav";
import SideBar from "@/app/Components/SideBar";
import Contact from "@/app/Components/Contact";
import Posts from "./Posts/page.jsx";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import styles from "../styles/allcss.module.css"
import { Client } from "@/utils/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Synergy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <ToastContainer
            position="top-center"
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light" />
          <Nav />
          <div className="flex lg:grid lg:grid-cols-4 lg:gap-10 justify-center">
            <div className="hidden lg:block lg:fixed lg:top-30 lg:left-0 lg:h-5/6 lg:w-60">
              <SideBar />
            </div>
            <div className={`w-full lg:col-start-2 lg:col-span-2 lg:h-screen lg:overflow-y-auto ${styles.scrollbar_hide}`}>
              <Client>{children}</Client>
            </div>
            <div className="hidden lg:block lg:fixed lg:right-0 lg:top-30 lg:h-5/6 lg:w-60">
              <Contact />
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
